// This file is auto-generated by scripts/sync-manifest-policy.mjs
// Do not edit manually.
export const EXPECTED_PERMISSION_POLICY_SHA256 = '651ed7085c3a8211cbd3dc712f2d10e1e38ad968efeebafba6230089eb4f0dc3';
