// This file is auto-generated by scripts/sync-manifest-policy.mjs
// Do not edit manually.
export const EXPECTED_PERMISSION_POLICY_SHA256 = '6259846e4cf0075b2ed4c60307459c5571a09a5f53f64f686e9a35bbd998196e';
